FROM postgres:15

# Instalar Python y dependencias
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-requests \
    python3-bs4 \
    python3-psycopg2 \
    && rm -rf /var/lib/apt/lists/*

# Establecer Python 3 como el intérprete predeterminado
RUN ln -sf /usr/bin/python3 /usr/bin/python

# Mantener el comportamiento predeterminado de la imagen postgres
CMD ["postgres"]
